const cardData = [
  { id: 1, imgSrc: 'https://api.lucerna-tech.com/storage/sub_services/5toS8xFNBwAAkvH4tMfVDuF4IQ2rCOTxdXmUrBL7.svg', title: 'IOS Apps', description: 'Exquisite, flawless, and seamless – Experience the expertise of our iOS app developers who craft a flawless app for your business.', 
    paragraph: "Are you in need of top-notch iOS app solutions that leave a lasting impression? Look no further! Lucerna Tech's well-versed developers are here to deliver excellence. Experience the expertise of our iOS app developers as they craft flawless and seamless apps tailor-made for your business. Our iOS App Solutions: Customized Excellence: Our developers create personalized iOS apps that align perfectly with your business goals, ensuring a unique and tailored experience for your users. Impeccable User Experience: We prioritize user-centric design, delivering apps that are not only visually stunning but also intuitive and delightful to use. Performance at its Finest: Our apps are optimized for optimal performance, ensuring speed, responsiveness, and reliability. Ongoing Support and Maintenance: We provide comprehensive support and maintenance services, ensuring your app stays up-to-date and performs flawlessly. Experience the pinnacle of iOS app development with Lucerna Tech. Contact us today to discuss your project, and let our well-versed developers craft an exceptional app that sets your business apart from the rest. Elevate your brand and engage your audience with our exquisite iOS app solutions." 
  },
  { id: 2, imgSrc: 'https://api.lucerna-tech.com/storage/sub_services/5aAgvhVf1FGakOLXwepNiRFuJbTng0DeBa9JwlRt.svg', title: 'Android Apps', description: 'Whether you want to build an Android app from scratch or fix the loopholes in your existing app, our Android app developers are here to deliver a feature-rich and fail-proof application that could help you in getting exponential growth and scalability.' },
  { id: 3, imgSrc: 'https://api.lucerna-tech.com/storage/sub_services/MEaJ3p8NNLo0CgXMj2lvo84XjgPTZDIkbQ59cVPn.svg', title: 'Cross Platform/Hybrid App', description: 'Integrate both iOS and Android platforms in a single yet powerful mobile app. With the help of cross-platform, our app developers help you to save time, effort, and simultaneously maximize efficiency.' },
  { id: 4, imgSrc: 'https://api.lucerna-tech.com/storage/sub_services/fnW2dA3t37eDSygg3fXTQCpQ1IfLxGFxDOj3806Z.svg', title: 'Mobile Wallets and Payments', description: 'Want to sell and upsell through payment management features? No worries. Our app developers help you with mobile wallets and payments.' },
  { id: 5, imgSrc: 'https://api.lucerna-tech.com/storage/sub_services/rLTlZDxPNXO5GcbR7o9Fa6AGvZjDfBrLIF0SiGzz.svg', title: 'Enterprise Mobile Solutions', description: 'Our experts offer a wide range of services and technologies tailored to meet the unique requirements of your business. We empower businesses by optimizing their workflows, enhancing productivity, and fostering effective communication.' },
  { id: 6, imgSrc: 'https://api.lucerna-tech.com/storage/sub_services/LCjQFJRmanUeJXGRRa5wqmeMS96mj9ESiKH0Qjdo.svg', title: 'REST API Backends', description: 'As a trusted provider of REST API backends, our highly skilled app developers at Lucerna Tech specialize in delivering robust and scalable solutions to meet your backend needs.' },
  { id: 7, imgSrc: 'https://api.lucerna-tech.com/storage/sub_services/4F6uDqOlECIWyVBnTvLnLymL30kI5ehLuYc73fFh.svg', title: 'IoT Apps', description: 'Our app developers specialize in delivering comprehensive solutions for the Internet of Things (IoT) ecosystem. By offering a wide range of services, we help businesses harness the power of IoT and create innovative applications.' },
];

export default cardData





